# Generated by Django 5.0.2 on 2025-03-05 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='name',
            new_name='title',
        ),
    ]
